# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da9461981b2f9b421c3c9f8da9ae6b2b8618cbaf8f3cac713269aa1335b10fe7ac5bf48aa8827b776f9c1e4fd4de82bd8676a8c80ae968839de97355e918afcc
  user: 'bobesponja'
  password: 'hakunamatata'

test:
  secret_key_base: d9384e868c96b8504c60107129c62a5416c57668d23eb2a158272aa4a9c8ce62f1d18c4b3469cdad8e84495d756ca9fc059dcbf75fd4f53302c60b528509c540

# Do not keep production secrets in the repository,
# instead read values from the environment.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  # username: bobesponja
  # password: [patrick]
